### ISSUE TITLE
 from optimum.version import __version__ ModuleNotFoundError: No module named 'optimum.version'

### ISSUE THREAD

**Issue by internetoftim** [huggingface/optimum-graphcore#23]
```
[21:09:16.438] [poptorch::python] [critical] ModuleNotFoundError: No module named'optimum.version'

Traceback (most recent call last):
  File "run_qa.py", line 31, in <module>
    from optimum.graphcore import IPUConfig
  File "/usr/local/lib/python3.6/dist-packages/optimum/graphcore/__init__.py", line 21, in <module>
    from .trainer import IPUTrainer
  File "/usr/local/lib/python3.6/dist-packages/optimum/graphcore/trainer.py", line 33, in <module>
    from optimum.version import __version__
ModuleNotFoundError: No module named 'optimum.version'
```

Fix:
Update line from dist-packages/optimum/graphcore/trainer.py
`from optimum.version import __version__ `>> `from optimum.graphcore.version import __version__`

**Comment by internetoftim** [comment]
When I do the above fix it leads to another issue:

```
[21:13:45.884] [poptorch::python] [critical] ImportError: cannot import name 'pad_on_batch_axis'

Traceback (most recent call last):
  File "run_qa.py", line 33, in <module>
    from optimum.graphcore.data import pad_on_batch_axis
ImportError: cannot import name 'pad_on_batch_axis'
```

**Comment by jimypbr** [comment]
Wrong installation issue. Closing.
