### ISSUE TITLE
Language modeling example fails

### ISSUE THREAD

**Issue by juliensimon** [huggingface/optimum-graphcore#38]
Using the latest source install (https://github.com/huggingface/optimum-graphcore/commit/d8b082ab341678ff2380eb15377a5ceea9c7c7f6), the language modeling example fails.

transformers.version
'4.16.2'
datasets.version
'1.18.3'
tokenizers.version
'1.11.5'

```
python run_pretraining.py   --config_name bert-base-uncased   --tokenizer_name bert-base-uncased   --ipu_config_name Graphcore/bert-base-ipu   --dataset_name Graphcore/wikipedia-bert-128   --do_train   --do_eval   --output_dir ./output/test-pretraining --cache_dir /localdata/juliens

02/17/2022 09:25:13 - INFO - __main__ - Training new model from scratch
Running tokenizer on every text in dataset:   0%|                                                                                                                                                            | 0/36728 [00:00<?, ?ba/s]
[09:25:16.219] [poptorch::python] [critical] ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Traceback (most recent call last):
  File "run_pretraining.py", line 626, in <module>
    main()
  File "run_pretraining.py", line 484, in main
    desc="Running tokenizer on every text in dataset",
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/dataset_dict.py", line 512, in map
    for k, dataset in self.items()
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/dataset_dict.py", line 512, in <dictcomp>
    for k, dataset in self.items()
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2120, in map
    desc=desc,
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/fingerprint.py", line 413, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2485, in _map_single
    offset=offset,
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2367, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2062, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "run_pretraining.py", line 475, in tokenize_function
    return tokenizer(examples[text_column_name], return_special_tokens_mask=True)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2418, in __call__
    "text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) "
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

02/17/2022 09:25:16 - critical - poptorch::python - ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Traceback (most recent call last):
  File "run_pretraining.py", line 626, in <module>
    main()
  File "run_pretraining.py", line 484, in main
    desc="Running tokenizer on every text in dataset",
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/dataset_dict.py", line 512, in map
    for k, dataset in self.items()
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/dataset_dict.py", line 512, in <dictcomp>
    for k, dataset in self.items()
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2120, in map
    desc=desc,
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/fingerprint.py", line 413, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2485, in _map_single
    offset=offset,
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2367, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 2062, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "run_pretraining.py", line 475, in tokenize_function
    return tokenizer(examples[text_column_name], return_special_tokens_mask=True)
  File "/home/juliens/optimum-env/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 2418, in __call__
    "text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) "
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

```

**Comment by jimypbr** [comment]
I updated the pretraining README with commands for phase 1 and phase 2 pretraining.
