### ISSUE TITLE
SQuAD eval: list index out of range in postprocess_qa_predictions

### ISSUE THREAD

**Issue by jimypbr** [huggingface/optimum-graphcore#44]
Get this error when running postprocessing of squad results:

```
02/21/2022 22:13:33 - critical - poptorch::python - IndexError: list index out of range

Traceback (most recent call last):
  File "examples/question-answering/run_qa.py", line 671, in <module>
    main()
  File "examples/question-answering/run_qa.py", line 628, in main
    metrics = trainer.evaluate()
  File "/localdata/jamesbr/dev/optimum-graphcore/examples/question-answering/trainer_qa.py", line 57, in evaluate
    eval_preds = self.post_process_function(eval_examples, eval_dataset, output.predictions)
  File "examples/question-answering/run_qa.py", line 573, in post_processing_function
    prefix=stage,
  File "/localdata/jamesbr/dev/optimum-graphcore/examples/question-answering/utils_qa.py", line 152, in postprocess_qa_predictions
    "offsets": (offset_mapping[start_index][0], offset_mapping[end_index][1]),
IndexError: list index out of range
```

Reproducer:
```
python examples/question-answering/run_qa.py \
  --ipu_config_name Graphcore/roberta-base-ipu \
  --model_name_or_path roberta-base \
  --dataset_name squad_v2 \
  --version_2_with_negative \
  --do_train False \
  --do_eval \
  --num_train_epochs 2 \
  --per_device_train_batch_size 4 \
  --per_device_eval_batch_size 2 \
  --learning_rate 6e-5 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --seed 1984 \
  --lr_scheduler_type cosine \
  --loss_scaling 64 \
  --weight_decay 0.01 \
  --warmup_ratio 0.25 \
  --logging_steps 10 \
  --save_steps 200 \
  --dataloader_num_workers 64 \
  --output_dir squad_roberta_base \
  --overwrite_output_dir
```

**Comment by jimypbr** [comment]
Possibly it's fixed by this from transformers: https://github.com/huggingface/transformers/commit/d0b5ed110aa034f21de3a1b4c043b44a7dc59c41
