### ISSUE TITLE
error of 'WhisperConfig for this kind of AutoModel: AutoModelForCTC'

### ISSUE THREAD

**Issue by YanyuanAI** [huggingface/optimum-graphcore#445]
Hi, I follow the readme.md to run the whisper example program, 
 pip install optimum[graphcore] optuna
and my Python package is like the below:
transformers==4.25.1
optimum==1.6.1       
optimum-graphcore ==0.6.1 
but when I run the run_whisper_pipeline.py, I got the error:
```
[05:08:47.252] [poptorch::python] [critical] ValueError: Unrecognized configuration class <class 'transformers.models.whisper.configuration_whisper.WhisperConfig'> for this kind of AutoModel: AutoModelForCTC.
Model type should be one of Data2VecAudioConfig, HubertConfig, MCTCTConfig, SEWConfig, SEWDConfig, UniSpeechConfig, UniSpeechSatConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WavLMConfig.

Traceback (most recent call last):
  File "run_whisper_pipeline.py", line 104, in <module>
    ipu_pipeline = pipeline(
  File "/localdata/cn-customer-engineering/xudongz/onnxfs2/fs2_/lib/python3.8/site-packages/optimum/graphcore/pipelines/__init__.py", line 366, in pipeline
    model = SUPPORTED_TASKS[targeted_task]["class"][0].from_pretrained(model_id, revision=revision)
  File "/localdata/cn-customer-engineering/xudongz/onnxfs2/fs2_/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 466, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.whisper.configuration_whisper.WhisperConfig'> for this kind of AutoModel: AutoModelForCTC.
Model type should be one of Data2VecAudioConfig, HubertConfig, MCTCTConfig, SEWConfig, SEWDConfig, UniSpeechConfig, UniSpeechSatConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WavLMConfig.
```

**Comment by jimypbr** [comment]
resolved in 0.7 release.
