### ISSUE TITLE
Running ViT run_image_classification_on_local_data.py produces error on replication factor

### ISSUE THREAD

**Issue by internetoftim** [huggingface/optimum-graphcore#74]
```
[19:14:25.212] [poptorch::python] [critical] AssertionError: Unexpected type <class 'dict'> for option replication_factor. Expected <class 'int'>

Traceback (most recent call last):
  File "run_image_classification_on_local_data.py", line 369, in <module>
    main()
  File "run_image_classification_on_local_data.py", line 333, in main
    data_collator=collate_fn,
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/trainer.py", line 225, in __init__
    self.opts = self.ipu_config.to_options()
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/ipu_configuration.py", line 251, in to_options
    return self.for_pod_type(pod_type)._to_options(for_inference=for_inference, compile_only=compile_only)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/ipu_configuration.py", line 136, in _to_options
    opts.replicationFactor(self.inference_replication_factor if for_inference else self.replication_factor)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/poptorch/options.py", line 1381, in replicationFactor
    self.set(replication_factor=replication_factor)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/poptorch/_options_impl.py", line 67, in set
    type(value), option, type(self._values[option]))
AssertionError: Unexpected type <class 'dict'> for option replication_factor. Expected <class 'int'>

03/25/2022 19:14:25 - critical - poptorch::python - AssertionError: Unexpected type <class 'dict'> for option replication_factor. Expected <class 'int'>

Traceback (most recent call last):
  File "run_image_classification_on_local_data.py", line 369, in <module>
    main()
  File "run_image_classification_on_local_data.py", line 333, in main
    data_collator=collate_fn,
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/trainer.py", line 225, in __init__
    self.opts = self.ipu_config.to_options()
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/ipu_configuration.py", line 251, in to_options
    return self.for_pod_type(pod_type)._to_options(for_inference=for_inference, compile_only=compile_only)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/ipu_configuration.py", line 136, in _to_options
    opts.replicationFactor(self.inference_replication_factor if for_inference else self.replication_factor)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/poptorch/options.py", line 1381, in replicationFactor
    self.set(replication_factor=replication_factor)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/poptorch/_options_impl.py", line 67, in set
    type(value), option, type(self._values[option]))
AssertionError: Unexpected type <class 'dict'> for option replication_factor. Expected <class 'int'>
```

I tried overriding `ipu_config_overrides="replication_factor=4,inference_replication_factor=4"` and it returns another error:

```
Overriding IPU config: replication_factor=4,inference_replication_factor=4
[19:19:46.420] [poptorch::python] [critical] ValueError: You can only update int, float, bool, list or string values in the config, got 4 for key replication_factor

Traceback (most recent call last):
  File "run_image_classification_on_local_data.py", line 369, in <module>
    main()
  File "run_image_classification_on_local_data.py", line 333, in main
    data_collator=collate_fn,
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/trainer.py", line 223, in __init__
    self.ipu_config.update_from_string(args.ipu_config_overrides)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/ipu_configuration.py", line 307, in update_from_string
    f"You can only update int, float, bool, list or string values in the config, got {v} for key {k}"
ValueError: You can only update int, float, bool, list or string values in the config, got 4 for key replication_factor

03/25/2022 19:19:46 - critical - poptorch::python - ValueError: You can only update int, float, bool, list or string values in the config, got 4 for key replication_factor

Traceback (most recent call last):
  File "run_image_classification_on_local_data.py", line 369, in <module>
    main()
  File "run_image_classification_on_local_data.py", line 333, in main
    data_collator=collate_fn,
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/trainer.py", line 223, in __init__
    self.ipu_config.update_from_string(args.ipu_config_overrides)
  File "/mnt/poddata/workspace/vit-hf/lib/python3.6/site-packages/optimum/graphcore/ipu_configuration.py", line 307, in update_from_string
    f"You can only update int, float, bool, list or string values in the config, got {v} for key {k}"
ValueError: You can only update int, float, bool, list or string values in the config, got 4 for key replication_factor
```

**Comment by jimypbr** [comment]
what's the command you are running? could you reinstall optimum-graphcore to the latest version of master and try again please?

**Comment by internetoftim** [comment]
```python3 run_image_classification_on_local_data.py  \
   --ipu_config_name Graphcore/vit-base-ipu \
    --train_dir /mnt/poddata/workspace/processed_images  \
    --train_val_split 0.1 \
    --output_dir ./outputs/ \
    --do_train \
    --do_eval \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --dataloader_num_workers 8 \
   --dataloader_drop_last \
    --num_train_epochs 6 \
    --seed 1337 \
    --logging_strategy steps    \
    --logging_steps 200   \
    --evaluation_strategy steps  \
    --save_strategy epoch  \
    --push_to_hub    \
   --push_to_hub_model_id vit_chestxray ```

**Comment by internetoftim** [comment]
I ran this from a fresh install as of 5pm today

**Comment by jimypbr** [comment]
How did you install it? Could you try with: `pip install git+https://github.com/huggingface/optimum-graphcore.git` ?

**Comment by jimypbr** [comment]
Fixed by installing from github with fresh environment
